language: node_js
node_js:
  - "10.15.0"

# config for Puppeteer
# https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-travis-ci
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install

script:
  - npm test
  - npm run build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: ap-northeast-1
    bucket: "cdn.form-input-recover.com"
    skip_cleanup: true
    local_dir: dist
    upload-dir: latest
    acl: public_read
    cache_control: "max-age=86400"
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: ap-northeast-1
    bucket: "cdn.form-input-recover.com"
    skip_cleanup: true
    local_dir: dist
    upload-dir: $TRAVIS_TAG
    acl: public_read
    cache_control: "max-age=31536000"
    on:
      tags: true